Winners/config/routes.rb
Rails.application.routes.draw do
  resources :stocks

end

Winners/app/models/stocastic.rb
class Stocastic < ActiveRecord::Base
end

Winners/app/models/stock.rb
class Stock < ActiveRecord::Base
end

Winners/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Winners/app/controllers/stocks_controller.rb
require "http"
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    #Create Request Address
    external = "http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol="
    external_request_address = external << stock_params["symbol"]

    #Retrive from External API
    variable = HTTP.get(external_request_address)
    @decodedJson = ActiveSupport::JSON.decode(variable)


    #Create Stocastic Model
    Stocastic.create(:symbol=>@decodedJson["Symbol"],
                      :price=>@decodedJson["LastPrice"],
                      :marketTime=>@decodedJson["Timestamp"])

=begin
    puts @decodedJson["Symbol"]
    puts @decodedJson["LastPrice"]
    puts @decodedJson["Timestamp"]
=end

    # multiple request via certain intevals
=begin
    begin
      # create HTTP client with persistent connection to api.icndb.com:
      http = HTTP.persistent "http://api.icndb.com"

      # issue multiple requests using same connection:
      100.times.map {
         jokes = http.get("/jokes/random").to_s
         puts jokes
         sleep 2
         puts "it acutually sleeps"
      }

    ensure
      # close underlying connection when you don't need it anymore
      http.close if http
    end
=end
    #Create HTTP Call
    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:symbol, :score)
    end
end

Winners/app/helpers/application_helper.rb
module ApplicationHelper
end

Winners/app/helpers/stocks_helper.rb
module StocksHelper
end

Winners/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Winners</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Winners/app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <!--
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Winners/app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

Winners/app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks Model To Train</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <!--
      <th>Score</th>
    -->
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.symbol %></td>
      <!--
        <td><%= stock.score %></td>
    -->
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

Winners/app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

Winners/app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @stock.symbol %>
</p>

<p>
  <strong>Score:</strong>
  <%= @stock.score %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>